version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/PlotPocket-BE/
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/remove_existing_files.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 600
      runas: ec2-user
  ApplicationStart:
    - location: scripts/restart_application.sh
      timeout: 300
      runas: ec2-user